### ISSUE TITLE
Enable multiple trait designations in mapping file

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-pipeline#1]
In term-mapping configuration file, need to enable multiple trait definitions:

e.g. 
name,description
"Flowers and Buds Present","{flowers present}, {buds present}"

This would get interpreted as two distinct observations (i think this is the case, need to verify this)

**Comment by rodney757** [comment]
I'll add it once you verify it should be 2 distinct observations

**Comment by jdeck88** [comment]
hold on this since i think we took care of this case by modifying the relevant ontology class

**Comment by jdeck88** [comment]
This is not necessary... i don't think we'll be doing this.
