### ISSUE TITLE
Insert Elevation based on location

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-pipeline#11]
Get Digital Elevation Model and put elevations in meters in the data in the pre-processor.

**Comment by rodney757** [comment]
do you have a dataset to use for this?

**Comment by jdeck88** [comment]
This has a couple of links that say you can download 30meter elevation data:
https://lpdaac.usgs.gov/dataset_discovery/aster/aster_products_table/astgtm

**Comment by jdeck88** [comment]
Based on conversation from jan. 19th won't do this.
