### ISSUE TITLE
Data compression

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-pipeline#12]
The data takes up a lot of space.  There are a few strategies here bundled in one issue needing to be implemented:

1. Represent trait data types in output_reasoned_csv using the obo prefix.

E.g. instead of:
http://purl.obolibrary.org/obo/PPO_0002013|http://purl.obolibrary.org/obo/PPO_0002000
represent as:
obo:PPO_0002013|obo:PPO_0002000

2. compress output... easy enough to gzip each file in output* directories.

3. Turn on ability for ElasticSearch to handle compressed input files (i think this should be a simple configuration switch -- it might already work).

**Comment by jdeck88** [comment]
After discussion decided we don't need #1 lets just use compression for sending data from CyVerse to UF

**Comment by rodney757** [comment]
I'm not sure this is worth doing, as I doubt think the connection speed is the bottleneck. If it isn't this would just slow down the process.

https://github.com/elastic/elasticsearch-py/issues/241#issuecomment-114484341

**Comment by jdeck88** [comment]
ok, labeled won't fix and closing
