### ISSUE TITLE
Fetch NPN data from API

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-pipeline#14]
I initially fetched NPN through the Web interface, however, we should
be fetching now from their API so we can more easily update and also, 
it seems get access to more data, 

The docs are here:
https://docs.google.com/document/d/1yNjupricKOAXn6tY1sI7-EwkcfwdGUZ7lxYv7fcPjO8/pub#h.w0nctgedhaop

In this api, i see dataset_id as an additional field, available by specifying additional_field as an input value and this would solve issue #9

**Comment by rodney757** [comment]
done
