### ISSUE TITLE
Climate Data Metrics

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-pipeline#2]
The following gives 5 degree x 5 degree reports on temperature variance by month going back to 1880:

https://www.ncdc.noaa.gov/data-access/marineocean-data/noaa-global-surface-temperature-noaaglobaltemp

In pipeline processing, lookup values given a decimal latitude / decimal longitude, month, and year for each variance listed and record with the output data.  

For triplifying, this is would a second measurement datum instance related to each observation.

**Comment by jdeck88** [comment]
1. This ECMWF data is based on weather station data and models, available on 3 hourly basis, Data is available from 1979 to Present. The following link gives the details of all the available data with them. The finest spatial resolution is 1 km.

https://www.ecmwf.int/en/research/climate-reanalysis/browse-reanalysis-datasets 

2. Then GHCN (Global Historical Climate Network) data is at a coarser resolution 5° by 5, but data goes from 1880. Below is the link for gridded data. But they also has daily weather station data. But will need krigging or some other technique to make it gridded. 

https://www.ncdc.noaa.gov/temp-and-precip/ghcn-gridded-products/

**Comment by jdeck88** [comment]
Rob suggested this dataset instead, which i think looks better than the GHCN product:

https://climatedataguide.ucar.edu/climate-data/cru-ts321-gridded-precipitation-and-other-meteorological-variables-1901

**Comment by rodney757** [comment]
the cru dataset is a bit of a pain. you need to register for an account to download. Also, I'm not sure which files to use. I tried downloading the 1901.2012.tmp.dat.gz from ftp://ftp.ceda.ac.uk/badc/cru/data/cru_ts/cru_ts_3.21/data/tmp/ and the 1901.2012.pre.dat.gz from ftp://ftp.ceda.ac.uk/badc/cru/data/cru_ts/cru_ts_3.21/data/pre

both files have nothing but -999 values from what I can tell

**Comment by jdeck88** [comment]
Here is another data product reccomended by Hank, looks like Global Scope going from 1948 to present:

https://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis.html

We will need to check on resolution/grid size

**Comment by jdeck88** [comment]
NCEP monthly mean average data has been added from the NCEP package.  There are other metrics available there which we may want to add in the future, however... going to close this issue until we can discover what other ones we may want.
