### ISSUE TITLE
NEON API/Data Ingest

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-pipeline#3]
Update the NEON data with new NEON formats.  

The NEON Phenology data can be downloaded from:
http://data.neonscience.org/data-product-view?dpCode=DP1.10055.001

Also it is available via the NEON API (which probably will give an easier route for incorporating updates):
From Christine Laney:
You’ve probably seen the documentation at http://data.neonscience.org/data-api. I’d recommend that you start with the products endpoint http://data.neonscience.org/api/v0/products/DP1.10055.001 which will give you the list of sites and months for which data are available. Then use this to populate a URL like http://data.neonscience.org/api/v0/data/DP1.10055.001/OAES/2016-05. Just beware that the URLs to the data files that are returned by your request are temporary.

**Comment by rodney757** [comment]
theres a script in the neon project directory to fetch the data using the api now
