### ISSUE TITLE
Customized default PEP fields

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-pipeline#6]
All PEP field declarations means that something is present.  We have four default fields that are used.  Since PEP does not have counts provided by the user, the default values are always used and consist of lower_percent, upper_percent, lower_count, and upper_count. 

See https://github.com/biocodellc/ppo-data-pipeline/blob/master/projects/pep725/phenophase_descriptions.csv

**Comment by rodney757** [comment]
this was already implemented
