### ISSUE TITLE
Triplifier recording rdfs:labels as types instead of URIs

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-pipeline#8]
The refactored triplifiers is recording plant traits using their rdfs:labels, such as:

```
<http://n2t.net/ark:/21547/Amf26795471> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Unripe seed cones"^^<http://www.w3.org/2001/XMLSchema#string> .
```
However, they have to be recorded as URIs, e.g.:

```
<http://n2t.net/ark:/21547/Amf26795471>
      a       obo:PPO_0002023 ;
```

This explains why files in the output_reasoned_csv directory both no longer have URIs and also no longer express multiple traits.  The multiple traits are all inferred during the reasoning step.  Having the labels in place of URIs prevents the reasoner from doing its job since it runs inferencing based on URI values not label values.

I think this issue happens around line 82 of triplifier.py where it searches for the value of the defined_by column.  What needs to happen is to substitute the value of for example, {non-senesced flower head presence} with the URI that is in the PPO.  In the pheno_paper repo, this happened in the biocode-fims-configurator codebase which had the code for searching for rdfs:labels within an ontology.   The ontopilot codebase actually contains this codebase now, and it is preferable to use ontopilot to write this new function instead of writing a new custom function,  since we want to enable searching for rdfs:labels across imports.

**Comment by rodney757** [comment]
what project is this for? This works correctly with asu data (running again to verify). Check the config files. We do perform label substitution across imports. The label substitution should happen when we populate the list in config.py.

Does the file coming out of the preprocessor have the column `phenophase_name`? That is the column we expect the phenophase_descriptions.csv fields to be under

**Comment by rodney757** [comment]
ah, I see the issue. There was a bug when I parsed the rules in config.py. I think this should be fixed now.

**Comment by jdeck88** [comment]
just ran it... yes fixed.
